### ISSUE TITLE
CamelAwssqsSinkConnector is leaking AWS credentials into Kafka Connect log

### ISSUE THREAD

**Issue by scholzj** [apache/camel-kafka-connector#320] opened 2020-07-14 18:43 UTC
While using the CamelAwssqsSinkConnector, it seems that it is quite easy to find the AWS credentials in the Connect log. One of the examples is the error mentioned in #319 ... but also after I switched to using the following options `camel.component.aws-sqs.access-key`, `camel.component.aws-sqs.secret-key`, `camel.component.aws-sqs.region` ... it for example prints the credentials directly into the log as well:

```
2020-07-14 11:39:30,563 INFO Auto-configuration summary: (org.apache.camel.main.BaseMainSupport) [pool-13-thread-1]
2020-07-14 11:39:30,563 INFO 	camel.component.aws-s3.region=US_EAST_1 (org.apache.camel.main.BaseMainSupport) [pool-13-thread-1]
2020-07-14 11:39:30,563 INFO 	camel.component.aws-s3.accessKey=AKIAIOSFODNN7EXAMPLE (org.apache.camel.main.BaseMainSupport) [pool-13-thread-1]
2020-07-14 11:39:30,563 INFO 	camel.component.aws-s3.secretKey=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY (org.apache.camel.main.BaseMainSupport) [pool-13-thread-1]
```

I think ideally they should be printed only in the masked form to make sure they cannot leak through the log.

**Comment by oscerd** [comment] 2020-07-14 18:49
The problem is related to the slash in the key.. we should use RAW(key)... In the endpoint definition. I'll have a look

**Comment by scholzj** [comment] 2020-07-14 18:53
Just FYI ... these are the Amazon example keys, not my real keys ;-) ... the actual key contained `+`. So I guess the problem might be the same.

**Comment by oscerd** [comment] 2020-07-15 05:26
duplicate of #159

**Closed by oscerd** 2020-07-15 05:26 UTC
