### ISSUE TITLE
AWS S3: bucket name not resolved when using URL configuration

### ISSUE THREAD

**Issue by orpiske** [apache/camel-kafka-connector#260] opened 2020-06-08 14:18 UTC
The bucket name does not seem to be resolved when using only the URL to set the source. 

Here's a snippet from a configuration file:

```
camel.source.url=aws-s3://ckc-s3?configuration=#class:org.apache.camel.kafkaconnector.source
.aws.s3.TestS3Configuration&accessKey=accesskey&secretKey=secretkey&protocol=http&region=US_EAST_1
tasks.max=1
topics=org.apache.camel.kafkaconnector.source.aws.s3.CamelSourceAWSS3ITCase
```

Then, during startup: 

```
INFO org.apache.camel.kafkaconnector.awss3.CamelAwss3SourceConnectorConfig - CamelAwss3SourceConnectorConfig values:
...
camel.source.path.bucketNameOrArn = null
```

To reproduce the problem run: 

`mvn -DskipIntegrationTests=false -Dmaven.test.failure.ignore=true -Dmaven.test.error.ignore=true -Dit.test=CamelSourceAWSS3ITCase\#testBasicSendReceiveUsingUrl clean test`

**Comment by oscerd** [comment] 2020-06-08 15:45
I get 

Caused by: org.apache.camel.ResolveEndpointFailedException: Failed to resolve endpoint: aws-s3://ckc-s3?accessKey=accesskey&configuration=%23class%3Aorg.apache.camel.kafkaconnector.source.aws.s3.TestS3Configuration&protocol=http&region=US_EAST_1&secretKey=xxxxxx due to: There are 1 parameters that couldn't be set on the endpoint. Check the uri if the parameters are spelt correctly and that they are properties of the endpoint. Unknown parameters=[{protocol=http}]

**Comment by orpiske** [comment] 2020-06-08 18:39
> I get
> 
> Caused by: org.apache.camel.ResolveEndpointFailedException: Failed to resolve endpoint: aws-s3://ckc-s3?accessKey=accesskey&configuration=%23class%3Aorg.apache.camel.kafkaconnector.source.aws.s3.TestS3Configuration&protocol=http&region=US_EAST_1&secretKey=xxxxxx due to: There are 1 parameters that couldn't be set on the endpoint. Check the uri if the parameters are spelt correctly and that they are properties of the endpoint. Unknown parameters=[{protocol=http}]

You are right. There is one more step that I forgot to mention: 
1. Comment the protocol parameter on [this line](https://github.com/apache/camel-kafka-connector/blob/f3e0ad9536cff4163198989e119495cb5a256dc6/tests/src/test/java/org/apache/camel/kafkaconnector/source/aws/s3/CamelSourceAWSS3ITCase.java#L167).

I found this while working on a separate PR and commented it after I noticed that it was causing an error on the logs. 

Then, you should get something like this on the logs:
```

2020-06-08 20:21:20,024 [ool-67-thread-1] ERROR org.apache.camel.impl.engine.AbstractCamelContext - Error starting CamelContext (camel-1) due to exception thrown: Failed to start route route1 because of null
org.apache.camel.FailedToStartRouteException: Failed to start route route1 because of null
        at org.apache.camel.impl.engine.RouteService.warmUp(RouteService.java:125) ~[camel-base-3.3.0.jar:3.3.0]
        at org.apache.camel.impl.engine.AbstractCamelContext.doWarmUpRoutes(AbstractCamelContext.java:3332) ~[camel-base-3.3.0.jar:3.3.0]
        at org.apache.camel.impl.engine.AbstractCamelContext.safelyStartRouteServices(AbstractCamelContext.java:3225) ~[camel-base-3.3.0.jar:3.3.0]
        at org.apache.camel.impl.engine.AbstractCamelContext.doStartOrResumeRoutes(AbstractCamelContext.java:3011) ~[camel-base-3.3.0.jar:3.3.0]
        at org.apache.camel.impl.engine.AbstractCamelContext.doStartCamel(AbstractCamelContext.java:2809) ~[camel-base-3.3.0.jar:3.3.0]
        at org.apache.camel.impl.engine.AbstractCamelContext.doStartContext(AbstractCamelContext.java:2662) [camel-base-3.3.0.jar:3.3.0]
        at org.apache.camel.impl.engine.AbstractCamelContext.doStart(AbstractCamelContext.java:2625) [camel-base-3.3.0.jar:3.3.0]
        at org.apache.camel.support.service.BaseService.start(BaseService.java:115) [camel-api-3.3.0.jar:3.3.0]
        at org.apache.camel.impl.engine.AbstractCamelContext.start(AbstractCamelContext.java:2467) [camel-base-3.3.0.jar:3.3.0]
        at org.apache.camel.main.Main.doStart(Main.java:118) [camel-main-3.3.0.jar:3.3.0]
        at org.apache.camel.support.service.BaseService.start(BaseService.java:115) [camel-api-3.3.0.jar:3.3.0]
        at org.apache.camel.main.MainSupport.run(MainSupport.java:83) [camel-main-3.3.0.jar:3.3.0]
        at org.apache.camel.kafkaconnector.utils.CamelMainSupport$CamelContextStarter.run(CamelMainSupport.java:234) [classes/:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.IllegalArgumentException: The bucket name parameter must be specified when listing objects in a bucket
        at com.amazonaws.services.s3.AmazonS3Client.rejectNull(AmazonS3Client.java:3864) ~[aws-java-sdk-s3-1.11.714.jar:?]
        at com.amazonaws.services.s3.AmazonS3Client.listObjects(AmazonS3Client.java:876) ~[aws-java-sdk-s3-1.11.714.jar:?]
        at org.apache.camel.component.aws.s3.S3Endpoint.doStart(S3Endpoint.java:102) ~[camel-aws-s3-3.3.0.jar:3.3.0]
        at org.apache.camel.support.service.BaseService.start(BaseService.java:115) ~[camel-api-3.3.0.jar:3.3.0]
        at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:84) ~[camel-api-3.3.0.jar:3.3.0]
        at org.apache.camel.impl.engine.RouteService.doWarmUp(RouteService.java:141) ~[camel-base-3.3.0.jar:3.3.0]
        at org.apache.camel.impl.engine.RouteService.warmUp(RouteService.java:123) ~[camel-base-3.3.0.jar:3.3.0]
        ... 15 more
```

**Comment by valdar** [comment] 2020-06-08 19:27
@orpiske can you post the complete config file please?

**Comment by orpiske** [comment] 2020-06-08 19:48
> @orpiske can you post the complete config file please?

Here's the config generated by the test: 

```
connector.class=org.apache.camel.kafkaconnector.awss3.CamelAwss3SourceConnector
camel.source.url=aws-s3://ckc-s3?configuration=#class:org.apache.camel.kafkaconnector.source.aws.s3.TestS3Configuration&accessKey=accesskey&secretKey=secretkey&region=US_EAST_1
tasks.max=1
topics=org.apache.camel.kafkaconnector.source.aws.s3.CamelSourceAWSS3ITCase
name=CamelAwss3SourceConnector
value.converter=org.apache.kafka.connect.storage.StringConverter
key.converter=org.apache.kafka.connect.storage.StringConverter
```

**Comment by valdar** [comment] 2020-06-11 23:07
Ok, after some investigation on why this is failing only if ran alone. I figured out that tests where not that isolated in regards to deleting topics in between tests.

The fix for this specific problem is just setting the S3 configuration object at the `component` level instead of doing it at the `endpoint` level see: https://github.com/apache/camel-kafka-connector/pull/272

**Comment by orpiske** [comment] 2020-06-12 08:54
> Ok, after some investigation on why this is failing only if ran alone. I figured out that tests where not that isolated in regards to deleting topics in between tests.
> 
> The fix for this specific problem is just setting the S3 configuration object at the `component` level instead of doing it at the `endpoint` level see: #272

Cool, thanks great! Thanks @valdar and sorry for the false negative!

**Closed** 2020-06-15 22:57 UTC
